#!/usr/bin/env bash
# Check sub domain is configured correctly.

# Function to check subdomains
check_subdomain() {
  local domain="$1"
  local subdomain="$2"

  if [ -z "$subdomain" ]; then
    subdomains=("www" "lb-01" "web-01" "web-02")
  else
    subdomains=("$subdomain")
  fi

  for sub in "${subdomains[@]}"; do
    result=$(dig "$sub.$domain" +short)

    if [ -z "$result" ]; then
      echo "The subdomain $sub is not configured or does not exist."
    else
      echo "The subdomain $sub is a A record and points to $result"
    fi
  done
}

# Check if both domain and subdomain parameters are provided
if [ $# -lt 1 ]; then
  echo "Usage: $0 <domain> [<subdomain>]"
  exit 1
fi

# Extract domain and subdomain from parameters
domain="$1"
subdomain="$2"

# Call the check_subdomain function
check_subdomain "$domain" "$subdomain"
