#!/usr/bin/env bash
# Install Nginx

sudo apt-get -y update
sudo apt-get install nginx -y

mkdir -p /var/www/html

echo 'Hello World!' > /var/www/html/index.html

cat > /etc/nginx/sites-available/default <<EOF
server {
    listen 80;
    server_name _;
    location / {
        root /var/www/html;
        index index.html;
    }
}
EOF

service nginx restart
