#!/usr/bin/env bash
# Install Nginx

apt install nginx -y
/etc/init.d/nginx start

cat > /etc/nginx/sites-available/default <<EOF
server {
    listen 80;
    server_name _;
    location / {
        echo "Hello World!";
    }
}
EOF

nginx -t
/etc/init.d/nginx reload
exit 0
