#!/usr/bin/env bash
# Not found page 404

sudo apt-get -y update

sudo apt-get -y install nginx
sudo mkdir -p /var/www/html
sudo sh -c 'echo "Hello World!" > /var/www/html/index.html'

sudo sed -i '/server_name _;/a \
        location /redirect_me {\n\
                rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n\
        }\n' /etc/nginx/sites-available/default
sudo service nginx restart
