#!/usr/bin/env bash
# Display surprise message on 4th and 8th else Best School

index=1
while [[  $index -lt 11  ]]; do
	if [[  $index = 4  ]]; then
		echo "bad luck"
	elif [[  $index = 8  ]]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( index++ ))
done
